title: LifeStack
baseurl: "" # leave empty for GitHub Pages
url: "https://skelleng.github.io/lifeStack"
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post