title: LifeStack
description: "A modular framework for intentional living: Cook, Clean, Build."
author: skelleng
url: "https://skelleng.github.io"
baseurl: "/lifeStack"
theme: jekyll-theme-minimal
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
